import gensim.downloader as api
'''
🔍 What This Means:
This is a 100-dimensional static word vector for the word 'sample' generated by the GloVe algorithm.

Unlike BERT, this embedding is not contextual — it’s fixed regardless of the sentence the word appears in.


'''
def Glove_demo():
    print("glove demo.......")
    model = api.load("glove-wiki-gigaword-100")  # You can also try 50, 200, 300
    print("Vector for 'sample':")
    print(model['sample'])  # Word vector for 'sample'

    print("\nMost similar to 'sample':")
    print(model.most_similar('sample'))
